name       : haskell-hi-file-parser
version    : 0.1.0.0
release    : 1
source     :
    - https://hackage.haskell.org/package/hi-file-parser-0.1.0.0/hi-file-parser-0.1.0.0.tar.gz : 54ac6750d5e4ef93c64b255f672261ae4c80ef11f20d92c382736e09be11fa25
license    : BSD-3-Clause
component  : programming.haskell
summary    : Parser for GHC's hi files
description: |
    Parser for GHC's hi files
builddeps  :
    - haskell-cabal-install
    - haskell-rio-devel
rundeps    :
    - devel:
        - haskell-rio-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
